# This will be your "logic layer" where
# all your backend classes live.
#Created by CoPilot

from dataclasses import dataclass, field
from typing import Optional, List, Tuple
from datetime import datetime, timedelta
import csv
import json
import numpy as np
import anthropic
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity


# -----------------------------------------------------------------------
# New skeleton generated by Claude (Anthropic AI).
# Note: Claude reads and considers all existing code before making edits
# or additions, so that new code fits the project's existing structure.
# -----------------------------------------------------------------------

@dataclass
class Task:
    """Represents a single care activity assigned to a pet."""
    task_id: int                # unique identifier for the task
    description: str            # what the task is, e.g. "Walk the dog"
    duration: int               # estimated time to complete, in minutes
    frequency: str              # how often, e.g. "daily", "weekly"
    time: str = "00:00"         # scheduled time in "HH:MM" format
    priority: str = "medium"    # "low", "medium", or "high"
    due_date: datetime = field(default_factory=datetime.now)  # when the task is due
    is_complete: bool = False   # whether the task has been completed

    def mark_complete(self) -> None:
        """Mark this task as completed."""
        self.is_complete = True

    def mark_incomplete(self) -> None:
        """Reset this task back to incomplete.
        
        Sets is_complete to False, reverting any completion status.
        Useful for unfinished or incorrectly marked tasks.
        """
        self.is_complete = False

    def edit_task(self, description: Optional[str] = None, 
                  duration: Optional[int] = None, 
                  frequency: Optional[str] = None) -> None:
        """Edit this task's description, duration, or frequency.
        
        Allows partial updates: pass only the fields you want to change.
        Useful for modifying task details without recreating the entire task.
        
        Args:
            description: New task description (e.g., "Walk the dog")
            duration: New estimated duration in minutes
            frequency: New frequency (e.g., "daily", "weekly")
        """
        if description is not None:
            self.description = description
        if duration is not None:
            self.duration = duration
        if frequency is not None:
            self.frequency = frequency


@dataclass
class Pet:
    """Stores pet details and the list of tasks assigned to that pet."""
    pet_id: int                         # unique identifier for the pet
    name: str                           # pet's name
    animal_type: str                    # e.g. "dog", "cat", "bird"
    tasks: List[Task] = field(default_factory=list)  # tasks belonging to this pet

    def add_task(self, task: Task) -> None:
        """Add a task to this pet's task list."""
        self.tasks.append(task)

    def remove_task(self, task: Task) -> None:
        """Remove a task from this pet's task list.
        
        Removes the specified task object from the pet's task list.
        Does nothing if the task is not in the list.
        
        Args:
            task: The task object to remove
        """
        if task in self.tasks:
            self.tasks.remove(task)

    def get_tasks(self) -> List[Task]:
        """Return all tasks assigned to this pet.
        
        Returns:
            List of Task objects assigned to this pet
        """
        return self.tasks


@dataclass
class Owner:
    """Manages multiple pets and provides access to all their tasks."""
    owner_id: int                        # unique identifier for the owner
    name: str                            # owner's full name
    email: str                           # owner's email address
    pets: List[Pet] = field(default_factory=list)  # all pets belonging to this owner

    def add_pet(self, pet: Pet) -> None:
        """Add a pet to this owner's pet list.
        
        Appends the pet to the pets list if not already present.
        Each pet can only be added once.
        
        Args:
            pet: The Pet object to add
        """
        if pet not in self.pets:
            self.pets.append(pet)

    def remove_pet(self, pet: Pet) -> None:
        """Remove a pet from this owner's pet list.
        
        Removes the specified pet and all its associated tasks.
        Does nothing if the pet is not in the list.
        
        Args:
            pet: The Pet object to remove
        """
        if pet in self.pets:
            self.pets.remove(pet)

    def get_all_tasks(self) -> List[Task]:
        """Return every task across all of this owner's pets.
        
        Flattens the hierarchical task structure: collects tasks from all pets
        and returns them as a single list. Useful for global scheduling operations.
        
        Returns:
            Combined list of all tasks from all pets
        """
        all_tasks = []
        for pet in self.pets:
            all_tasks.extend(pet.get_tasks())
        return all_tasks


@dataclass
class Scheduler:
    """The brain — retrieves, organizes, and manages tasks across all pets."""
    owner: Owner                         # the owner whose tasks are being scheduled

    def get_pending_tasks(self) -> List[Task]:
        """Return all incomplete tasks across every pet.
        
        Filters and returns tasks with is_complete == False.
        Useful for displaying a todo list or tracking outstanding work.
        
        Returns:
            List of incomplete Task objects
        """
        return self.filter_by_completion_status(False)

    def get_completed_tasks(self) -> List[Task]:
        """Return all completed tasks across every pet.
        
        Filters and returns tasks with is_complete == True.
        Useful for viewing completed work and task history.
        
        Returns:
            List of completed Task objects
        """
        return self.filter_by_completion_status(True)

    def sort_tasks_by_duration(self) -> List[Task]:
        """Return all tasks sorted from shortest to longest duration.
        
        Uses a lambda function to sort by duration in ascending order.
        Useful for prioritizing quick tasks or scheduling efficiency.
        
        Returns:
            List of tasks sorted by duration (shortest first)
        """
        all_tasks = self.owner.get_all_tasks()
        return sorted(all_tasks, key=lambda task: task.duration)

    def sort_tasks_by_frequency(self) -> List[Task]:
        """Return tasks grouped or sorted by frequency.
        
        Groups tasks by frequency type (daily, weekly, one-time, etc)
        and sorts them within each group by due date.
        Useful for understanding recurring vs. one-time workload patterns.
        
        Returns:
            List of tasks grouped and sorted by frequency
        """
        all_tasks = self.owner.get_all_tasks()
        # Sort by frequency first (as primary key) then by due date (as secondary key)
        return sorted(all_tasks, key=lambda task: (task.frequency, task.due_date))

    def get_tasks_for_pet(self, pet: Pet) -> List[Task]:
        """Return all tasks assigned to a specific pet.
        
        Filters global task list to return only tasks for the given pet.
        Equivalent to calling pet.get_tasks() directly.
        
        Args:
            pet: The Pet object to retrieve tasks for
            
        Returns:
            List of tasks assigned to the specified pet
        """
        return pet.get_tasks()

    def _time_to_minutes(self, time_str: str) -> int:
        """Helper: Convert "HH:MM" to total minutes for sorting.
        
        Args:
            time_str: Time in "HH:MM" format
            
        Returns:
            Total minutes since midnight
        """
        hours, minutes = map(int, time_str.split(':'))
        return hours * 60 + minutes

    def sort_by_time(self) -> List[Task]:
        """Return all tasks sorted by scheduled time in "HH:MM" format (earliest first)."""
        all_tasks = self.owner.get_all_tasks()
        return sorted(all_tasks, key=lambda task: self._time_to_minutes(task.time))

    def filter_by_completion_status(self, is_complete: bool) -> List[Task]:
        """Filter tasks by completion status. Pass True for completed, False for pending."""
        all_tasks = self.owner.get_all_tasks()
        return [task for task in all_tasks if task.is_complete == is_complete]

    def filter_by_pet_name(self, pet_name: str) -> List[Task]:
        """Return all tasks assigned to a pet with the specified name."""
        pet = next((pet for pet in self.owner.pets if pet.name == pet_name), None)
        if pet is None:
            return []
        return pet.tasks

    def filter_tasks(self, is_complete: Optional[bool] = None, pet_name: Optional[str] = None) -> List[Task]:
        """Filter tasks by completion status and/or pet name.
        
        Args:
            is_complete: True for completed, False for pending, None for all
            pet_name: Filter by pet name, None for all pets
        
        Returns:
            List of tasks matching the filter criteria
        """
        all_tasks = self.owner.get_all_tasks()
        
        # Filter by completion status if specified
        if is_complete is not None:
            all_tasks = [task for task in all_tasks if task.is_complete == is_complete]
        
        # Filter by pet name if specified
        if pet_name is not None:
            pet = next((pet for pet in self.owner.pets if pet.name == pet_name), None)
            if pet is None:
                return []
            all_tasks = [task for task in all_tasks if task in pet.tasks]
        
        return all_tasks

    def complete_task_with_recurrence(self, task: Task, pet: Pet) -> Optional[Task]:
        """Mark a task complete and create the next occurrence if it's recurring.
        
        Uses timedelta to calculate accurate next due dates:
        - Daily tasks: due_date + 1 day
        - Weekly tasks: due_date + 7 days
        
        Args:
            task: The task to mark as complete
            pet: The pet the task belongs to
            
        Returns:
            The next task instance if recurring, None if one-time task
        """
        task.mark_complete()
        
        # If not recurring, don't create a new task
        if task.frequency not in ["daily", "weekly"]:
            return None
        
        # Calculate next due date using timedelta
        if task.frequency == "daily":
            next_due_date = task.due_date + timedelta(days=1)
        else:  # weekly
            next_due_date = task.due_date + timedelta(days=7)
        
        # Create the next task instance
        next_task = Task(
            task_id=task.task_id + 1000,  # Generate a new unique ID
            description=task.description,
            duration=task.duration,
            frequency=task.frequency,
            time=task.time,
            priority=task.priority,
            due_date=next_due_date,
            is_complete=False
        )
        
        # Add the new task to the pet
        pet.add_task(next_task)
        
        return next_task

    def detect_scheduling_conflicts(self) -> List[str]:
        """Detect time conflicts across all tasks and return warning messages.
        
        Lightweight strategy: Groups tasks by due_date and time, then flags duplicates.
        Returns warnings instead of raising exceptions - program continues safely.
        
        Returns:
            List of warning messages for each conflict detected
        """
        warnings = []
        all_tasks = self.owner.get_all_tasks()
        
        # Group tasks by (due_date, time) for efficient conflict detection
        schedule_map = {}
        for pet in self.owner.pets:
            for task in pet.tasks:
                # Create a key from due date and time (ignore the time of day, just date + scheduled time)
                date_key = task.due_date.date()
                time_key = task.time
                schedule_key = (date_key, time_key)
                
                if schedule_key not in schedule_map:
                    schedule_map[schedule_key] = []
                schedule_map[schedule_key].append((pet.name, task))
        
        # Check for conflicts (multiple tasks at same time)
        for (date, time), tasks_at_slot in schedule_map.items():
            if len(tasks_at_slot) > 1:
                pet_names = [pet_name for pet_name, _ in tasks_at_slot]
                task_descriptions = [task.description for _, task in tasks_at_slot]
                
                warning = f"⚠️  SCHEDULING CONFLICT on {date} at {time}: {len(tasks_at_slot)} tasks scheduled\n"
                warning += f"   Pets: {', '.join(pet_names)}\n"
                warning += f"   Tasks: {' | '.join(task_descriptions)}"
                warnings.append(warning)
        
        return warnings

    def check_conflicts_and_add_task(self, pet: Pet, task: Task) -> Tuple[Task, List[str]]:
        """Add a task to a pet and return any scheduling conflicts.
        
        Safe wrapper that adds task and reports conflicts without crashing.
        
        Args:
            pet: The pet to add the task to
            task: The task to add
            
        Returns:
            Tuple of (added_task, warning_messages)
        """
        pet.add_task(task)
        conflicts = self.detect_scheduling_conflicts()
        return task, conflicts


@dataclass
class EmbeddingManager:
    """Manages vector embeddings for the decision corpus used in RAG retrieval.
    
    This class handles the conversion of decision text into vector embeddings
    and maintains the embeddings file for efficient similarity search.
    """
    
    csv_file: str = "decisions.csv"  # Path to the decisions CSV file
    embeddings_file: str = "decisions_embeddings.npy"  # Path to the embeddings numpy file
    model_name: str = "all-MiniLM-L6-v2"  # Pre-trained sentence transformer model
    
    def __post_init__(self):
        """Initialize the sentence transformer model."""
        self.model = SentenceTransformer(self.model_name)
    
    def load_decisions(self) -> List[dict]:
        """Load all decisions from the CSV file.
        
        Returns:
            List of decision dictionaries with keys: date, request, proposal, outcome, final_task
        """
        decisions = []
        try:
            with open(self.csv_file, 'r', newline='', encoding='utf-8') as csvfile:
                reader = csv.DictReader(csvfile)
                for row in reader:
                    decisions.append(row)
        except FileNotFoundError:
            # If CSV doesn't exist yet, return empty list
            pass
        return decisions
    
    def create_embedding_text(self, decision: dict) -> str:
        """Create the text to embed from a decision dictionary.
        
        Combines request, proposal, and outcome for comprehensive similarity matching.
        
        Args:
            decision: Dictionary containing decision data
            
        Returns:
            Combined text string for embedding
        """
        return f"Request: {decision['request']}\nProposal: {decision['proposal']}\nOutcome: {decision['outcome']}"
    
    def generate_embeddings(self, decisions: List[dict]) -> np.ndarray:
        """Generate embeddings for a list of decisions.
        
        Args:
            decisions: List of decision dictionaries
            
        Returns:
            Numpy array of embeddings with shape (num_decisions, embedding_dim)
        """
        if not decisions:
            # Return empty array with correct shape
            return np.empty((0, self.model.get_sentence_embedding_dimension()))
        
        embedding_texts = [self.create_embedding_text(decision) for decision in decisions]
        embeddings = self.model.encode(embedding_texts, show_progress_bar=False)
        return embeddings
    
    def update_embeddings_file(self) -> None:
        """Update the embeddings file with current decisions from CSV.
        
        Loads all decisions, generates fresh embeddings, and saves to numpy file.
        This should be called whenever decisions are added to maintain consistency.
        """
        decisions = self.load_decisions()
        embeddings = self.generate_embeddings(decisions)
        
        # Save embeddings to file
        np.save(self.embeddings_file, embeddings)
        
        print(f"✅ Updated embeddings: {len(decisions)} decisions, shape {embeddings.shape}")
    
    def load_embeddings(self) -> Tuple[np.ndarray, List[dict]]:
        """Load embeddings and corresponding decisions from files.
        
        Returns:
            Tuple of (embeddings_array, decisions_list)
        """
        try:
            embeddings = np.load(self.embeddings_file)
            decisions = self.load_decisions()
            return embeddings, decisions
        except FileNotFoundError:
            return np.empty((0, self.model.get_sentence_embedding_dimension())), []
    
    def retrieve_similar_decisions(self, query: str, top_k: int = 3) -> List[dict]:
        """Retrieve the top-k most similar past decisions for a given query.
        
        Uses cosine similarity to find decisions most similar to the query.
        This is the core retrieval function for the RAG pipeline.
        
        Args:
            query: The user's task request (e.g., "Schedule vet appointment for Mochi")
            top_k: Number of similar decisions to return (default: 3)
            
        Returns:
            List of top-k similar decision dictionaries, sorted by similarity (most similar first)
        """
        # Load current embeddings and decisions
        embeddings, decisions = self.load_embeddings()
        
        if len(decisions) == 0 or len(embeddings) == 0:
            return []
        
        # Generate embedding for the query
        query_embedding = self.model.encode([query])[0]  # Shape: (embedding_dim,)
        
        # Compute cosine similarities between query and all stored embeddings
        similarities = cosine_similarity([query_embedding], embeddings)[0]  # Shape: (num_decisions,)
        
        # Get indices of top-k most similar decisions
        top_indices = np.argsort(similarities)[::-1][:top_k]  # Sort descending, take top_k
        
        # Return the corresponding decisions
        similar_decisions = []
        for idx in top_indices:
            decision = decisions[idx].copy()
            decision['similarity_score'] = float(similarities[idx])
            similar_decisions.append(decision)
        
        return similar_decisions

    def build_prompt(self, request: str, top_k: int = 3) -> str:
        """Build a retrieval-augmented prompt using the top similar past decisions.
        
        This method injects the top-k retrieved examples into a prompt template,
        grounding the agent's proposal in real prior decisions and outcomes.
        """
        similar_decisions = self.retrieve_similar_decisions(request, top_k=top_k)
        prompt_lines = [
            "You are a pet care planning assistant.",
            "Use the examples below to generate a grounded task proposal:",
            "",
        ]

        if similar_decisions:
            for index, decision in enumerate(similar_decisions, start=1):
                prompt_lines.append(f"Example {index}:")
                prompt_lines.append(f"Request: {decision['request']}")
                prompt_lines.append(f"Proposal: {decision['proposal']}")
                prompt_lines.append(f"Outcome: {decision['outcome']}")
                final_task = decision.get('final_task', '')
                if final_task:
                    prompt_lines.append(f"Final task: {final_task}")
                prompt_lines.append(f"Similarity: {decision['similarity_score']:.3f}")
                prompt_lines.append("")
        else:
            prompt_lines.append("No past decision examples are available yet.")
            prompt_lines.append("")

        prompt_lines.extend([
            "Current task request:",
            f"{request}",
            "",
            "Based on the examples above, propose a single grounded task plan for the current request.",
            "Include a clear scheduling suggestion and a brief rationale.",
            "Do not actually save the task until the user confirms.",
        ])

        return "\n".join(prompt_lines)

    def generate_task_proposal(self, request: str, existing_tasks: List = None) -> dict:
        """Call Claude to generate a structured task proposal grounded in past decisions.

        Returns a dict with keys: description, time, date, frequency, duration, priority, rationale.
        """
        today = datetime.now().strftime("%Y-%m-%d")
        similar_decisions = self.retrieve_similar_decisions(request, top_k=3)

        approved, rejected = [], []
        for d in similar_decisions:
            (approved if d.get("outcome") == "approved" else rejected).append(d)

        approved_section = "\n".join(
            f"- Request: {d['request']} | Final task: {d.get('final_task', '')}"
            for d in approved
        ) or "None."

        rejected_section = "\n".join(
            f"- Request: {d['request']} | Rejected proposal: {d.get('proposal', '')}"
            for d in rejected
        ) or "None."

        task_lines = []
        if existing_tasks:
            for t in existing_tasks:
                task_lines.append(
                    f"- {t.description} at {t.time}, {t.duration} min, {t.frequency}, {t.priority} priority"
                )
        tasks_section = "\n".join(task_lines) if task_lines else "No existing tasks."

        prompt = f"""Today is {today}.

Previously APPROVED proposals (use these as positive examples):
{approved_section}

Previously REJECTED proposals (do NOT repeat these — propose something meaningfully different in time, frequency, or approach):
{rejected_section}

Already scheduled tasks (choose a time that does not conflict):
{tasks_section}

User request: {request}

Respond with ONLY a valid JSON object — no markdown, no explanation, no extra text:
{{
  "description": "clear task name",
  "time": "HH:MM",
  "date": "YYYY-MM-DD",
  "frequency": "daily or weekly or monthly",
  "duration": <integer minutes>,
  "priority": "low or medium or high",
  "rationale": "one sentence explaining your scheduling choices"
}}"""

        client = anthropic.Anthropic()
        message = client.messages.create(
            model="claude-sonnet-4-6",
            max_tokens=512,
            system="You are a pet care scheduling assistant. Always respond with valid JSON only.",
            messages=[{"role": "user", "content": prompt}],
        )

        raw = message.content[0].text.strip()
        if raw.startswith("```"):
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
        return json.loads(raw.strip())


@dataclass
class DecisionLogger:
    """Logs past task decisions (approved, edited, rejected) to CSV for RAG retrieval.
    
    This class maintains a persistent record of all AI-generated proposals and user responses,
    building a corpus that improves future recommendations through similarity-based retrieval.
    """
    
    csv_file: str = "decisions.csv"  # Path to the decisions CSV file
    embedding_manager: EmbeddingManager = field(default_factory=EmbeddingManager)  # Manages embeddings
    
    def log_decision(self, request: str, proposal: str, outcome: str, final_task: str = "") -> None:
        """Log a single decision to the CSV file.
        
        Appends a new row to decisions.csv with the current timestamp and decision details.
        This creates the training data for the RAG retrieval system.
        
        Args:
            request: The user's original task request (e.g., "Schedule vet appointment")
            proposal: The AI-generated proposal (e.g., "Schedule on 2024-01-15 at 10:00")
            outcome: User's response - "approved", "edited", or "rejected"
            final_task: The final task description if approved/edited, empty if rejected
        """
        current_date = datetime.now().strftime("%Y-%m-%d")
        
        # Prepare the new row
        new_row = {
            'date': current_date,
            'request': request,
            'proposal': proposal,
            'outcome': outcome,
            'final_task': final_task
        }
        
        # Append to CSV file
        with open(self.csv_file, 'a', newline='', encoding='utf-8') as csvfile:
            fieldnames = ['date', 'request', 'proposal', 'outcome', 'final_task']
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            writer.writerow(new_row)
        
        print(f"✅ Logged decision: {outcome} - {request}")
        
        # Update embeddings after logging decision
        self.embedding_manager.update_embeddings_file()


# -----------------------------------------------------------------------
# Previous skeleton (CoPilot + Claude iteration 1) — kept for reference
# -----------------------------------------------------------------------

# @dataclass
# class OwnerInfo:
#     """Stores owner's personal information and pet count."""
#     owner_id: int
#     name: str
#     email: str
#     phone: str
#     number_of_pets: int = 0
#
#     def add_owner_info(self) -> None:
#         """Add owner information to the system."""
#         # Validate required fields
#         if not self.name or not self.email or not self.phone:
#             raise ValueError("Name, email, and phone are required")
#         # Basic email validation
#         if "@" not in self.email:
#             raise ValueError("Invalid email format")
#         if self.number_of_pets < 0:
#             raise ValueError("Number of pets cannot be negative")
#         # In a real system, this would save to database
#         print(f"Owner '{self.name}' added successfully")
#
#     def edit_owner_info(self) -> None:
#         """Edit the owner's information."""
#         # Validate required fields
#         if not self.name or not self.email or not self.phone:
#             raise ValueError("Name, email, and phone are required")
#         # Basic email validation
#         if "@" not in self.email:
#             raise ValueError("Invalid email format")
#         if self.number_of_pets < 0:
#             raise ValueError("Number of pets cannot be negative")
#         # In a real system, this would update in database
#         print(f"Owner '{self.name}' updated successfully")


# @dataclass
# class PetInfo:
#     """Stores individual pet information and metadata."""
#     pet_id: int
#     owner_id: int
#     pet_name: str
#     animal_type: str
#     breed: Optional[str] = None
#     age: Optional[int] = None
#
#     def add_pet(self) -> None:
#         """Add a new pet to the system."""
#         # Validate required fields
#         if not self.pet_name or not self.animal_type:
#             raise ValueError("Pet name and animal type are required")
#         if self.age is not None and self.age < 0:
#             raise ValueError("Age cannot be negative")
#         # In a real system, this would save to database
#         print(f"Pet '{self.pet_name}' added successfully")
#
#     def edit_pet(self) -> None:
#         """Edit the pet's information."""
#         # Validate required fields
#         if not self.pet_name or not self.animal_type:
#             raise ValueError("Pet name and animal type are required")
#         if self.age is not None and self.age < 0:
#             raise ValueError("Age cannot be negative")
#         # In a real system, this would update in database
#         print(f"Pet '{self.pet_name}' updated successfully")


# @dataclass
# class Task:
#     """Stores individual task/activity information."""
#     task_id: int
#     owner_id: int
#     task_name: str
#     duration: int  # in minutes
#     priority: int  # 1-5 or similar scale
#     created_at: datetime = field(default_factory=datetime.now)
#     assigned_pet: Optional[PetInfo] = None
#
#     def create_task(self) -> None:
#         """Create a new task."""
#         # Validate required fields
#         if not self.task_name:
#             raise ValueError("Task name is required")
#         if self.duration <= 0:
#             raise ValueError("Duration must be positive")
#         if not (1 <= self.priority <= 5):
#             raise ValueError("Priority must be between 1 and 5")
#         # In a real system, this would save to database
#         print(f"Task '{self.task_name}' created successfully")
#
#     def edit_task(self) -> None:
#         """Edit the task's information."""
#         # Validate required fields
#         if not self.task_name:
#             raise ValueError("Task name is required")
#         if self.duration <= 0:
#             raise ValueError("Duration must be positive")
#         if not (1 <= self.priority <= 5):
#             raise ValueError("Priority must be between 1 and 5")
#         # In a real system, this would update in database
#         print(f"Task '{self.task_name}' updated successfully")
#
#     def delete_task(self) -> None:
#         """Delete the task."""
#         # In a real system, this would remove from database
#         print(f"Task '{self.task_name}' deleted successfully")


# @dataclass
# class TaskList:
#     """Organizes and displays tasks, filtered by priority or chronological order."""
#     list_id: int
#     owner_id: int
#     list_name: str
#     sort_by: str  # "priority" or "createdDate"
#     tasks: List[Task] = field(default_factory=list)
#
#     def add_task(self, task: Task) -> None:
#         """Add a task to the list."""
#         if task.owner_id != self.owner_id:
#             raise ValueError("Task must belong to the same owner as the list")
#         if task not in self.tasks:
#             self.tasks.append(task)
#             print(f"Task '{task.task_name}' added to list '{self.list_name}'")
#         else:
#             print(f"Task '{task.task_name}' is already in the list")
#
#     def remove_task(self, task: Task) -> None:
#         """Remove a task from the list."""
#         if task in self.tasks:
#             self.tasks.remove(task)
#             print(f"Task '{task.task_name}' removed from list '{self.list_name}'")
#         else:
#             print(f"Task '{task.task_name}' not found in the list")
#
#     def get_tasks(self) -> List[Task]:
#         """Get all tasks in the list, sorted by priority or date."""
#         if self.sort_by == "priority":
#             return sorted(self.tasks, key=lambda t: t.priority)
#         elif self.sort_by == "createdDate":
#             return sorted(self.tasks, key=lambda t: t.created_at)
#         else:
#             # Default to priority if invalid sort_by
#             return sorted(self.tasks, key=lambda t: t.priority)
#
#     def update_sort_order(self, sort_by: str) -> None:
#         """Update the sort order (priority or createdDate)."""
#         if sort_by not in ["priority", "createdDate"]:
#             raise ValueError("Sort order must be 'priority' or 'createdDate'")
#         self.sort_by = sort_by
#         print(f"Sort order updated to '{sort_by}' for list '{self.list_name}'")


# -----------------------------------------------------------------------
# Claude iteration 1 skeleton (based on original UML) — kept for reference
# -----------------------------------------------------------------------

# @dataclass
# class PetInfo:
#     """Stores individual pet information and metadata."""
#     pet_id: int           # unique identifier for each pet
#     pet_name: str         # name of the pet
#     animal_type: str      # e.g. "dog", "cat", "bird"
#     breed: Optional[str] = None   # optional breed info
#     age: Optional[int] = None     # optional age in years
#
#     def enter_pet_info(self) -> None:
#         """Enter a new pet's information into the system."""
#         pass
#
#     def edit_pet_info(self) -> None:
#         """Edit this pet's existing information."""
#         pass


# @dataclass
# class Task:
#     """Stores individual task/activity information."""
#     task_id: int            # unique identifier for each task
#     task_name: str          # e.g. "Walk the dog"
#     duration: int           # estimated time to complete, in minutes
#     priority: str           # "high", "medium", or "low"
#     date_added: datetime = field(default_factory=datetime.now)  # auto-set on creation
#     assigned_pet: Optional[PetInfo] = None  # optionally link task to a specific pet
#
#     def create_task(self) -> None:
#         """Create a new task and add it to the system."""
#         pass
#
#     def edit_task(self) -> None:
#         """Edit this task's information."""
#         pass
#
#     def delete_task(self) -> None:
#         """Delete this task from the system."""
#         pass


# @dataclass
# class TaskList:
#     """Organizes and displays tasks sorted by priority or input order."""
#     tasks: List[Task] = field(default_factory=list)  # starts as an empty list
#
#     def add_task(self, task: Task) -> None:
#         """Add a task to the list."""
#         pass
#
#     def remove_task(self, task: Task) -> None:
#         """Remove a task from the list."""
#         pass
#
#     def sort_by_priority(self) -> List[Task]:
#         """Return tasks sorted by priority: high -> medium -> low."""
#         pass
#
#     def sort_by_date_added(self) -> List[Task]:
#         """Return tasks in the order they were originally added."""
#         pass
#
#     def display_list(self) -> None:
#         """Print all tasks currently in the list."""
#         pass


# @dataclass
# class OwnerInfo:
#     """Stores owner personal info, their pets, and their task list."""
#     owner_id: int           # unique identifier for the owner
#     owner_name: str         # full name of the owner
#     email: str              # owner's email address
#     phone: str              # owner's phone number
#     pets: List[PetInfo] = field(default_factory=list)        # list of owner's pets
#     task_list: TaskList = field(default_factory=TaskList)    # owner's task list
#
#     @property
#     def number_of_pets(self) -> int:
#         """Derived from the pets list — stays accurate without manual tracking."""
#         return len(self.pets)
#
#     def enter_info(self) -> None:
#         """Enter the owner's personal information into the system."""
#         pass
#
#     def edit_info(self) -> None:
#         """Edit the owner's existing personal information."""
#         pass
#
#     def add_pet(self, pet: PetInfo) -> None:
#         """Add a pet to this owner's pet list."""
#         pass
#
#     def remove_pet(self, pet: PetInfo) -> None:
#         """Remove a pet from this owner's pet list."""
#         pass
